"""
Adapters pour la persistence des donnees.

Ce module expose les repositories et le DatabaseManager
pour l'architecture hexagonale.
"""

from src.infrastructure.persistence.sqlalchemy_page_repository import SQLAlchemyPageRepository
from src.infrastructure.persistence.sqlalchemy_winning_ad_repository import (
    SQLAlchemyWinningAdRepository,
)

# Database module (migre depuis app/)
from src.infrastructure.persistence.database import (
    # Base SQLAlchemy
    Base,
    DatabaseManager,
    # Models
    PageRecherche,
    SuiviPage,
    AdsRecherche,
    Blacklist,
    WinningAds,
    Tag,
    PageTag,
    PageNote,
    Favorite,
    Collection,
    CollectionPage,
    SavedFilter,
    ScheduledScan,
    UserSettings,
    ClassificationTaxonomy,
    MetaToken,
    TokenUsageLog,
    AppSettings,
    SearchLog,
    PageSearchHistory,
    WinningAdSearchHistory,
    SearchQueue,
    APICallLog,
    SuiviPageArchive,
    AdsRechercheArchive,
    WinningAdsArchive,
    APICache,
    # Functions
    ensure_tables_exist,
    get_etat_from_ads_count,
    to_str_list,
    get_app_setting,
    set_app_setting,
    get_all_app_settings,
    save_pages_recherche,
    save_suivi_page,
    save_ads_recherche,
    get_all_pages,
    get_page_history,
    get_suivi_stats,
    get_suivi_stats_filtered,
    get_dashboard_trends,
    get_suivi_history,
    search_pages,
    add_country_to_page,
    add_countries_to_pages_batch,
    get_all_countries,
    get_all_subcategories,
    get_cached_pages_info,
    get_evolution_stats,
    get_page_evolution_history,
    add_to_blacklist,
    remove_from_blacklist,
    get_blacklist,
    is_in_blacklist,
    get_blacklist_ids,
    is_winning_ad,
    save_winning_ads,
    cleanup_duplicate_winning_ads,
    record_page_search_history,
    record_winning_ad_search_history,
    record_pages_search_history_batch,
    record_winning_ads_search_history_batch,
    get_pages_for_search,
    get_winning_ads_for_search,
    get_searches_for_page,
    get_search_history_stats,
    get_winning_ads,
    get_winning_ads_filtered,
    get_winning_ads_stats_filtered,
    get_winning_ads_stats,
    get_winning_ads_by_page,
    get_all_tags,
    create_tag,
    delete_tag,
    add_tag_to_page,
    remove_tag_from_page,
    get_page_tags,
    get_pages_by_tag,
)

__all__ = [
    # Repositories
    "SQLAlchemyPageRepository",
    "SQLAlchemyWinningAdRepository",
    # Core
    "Base",
    "DatabaseManager",
    # Models
    "PageRecherche",
    "SuiviPage",
    "AdsRecherche",
    "Blacklist",
    "WinningAds",
    "Tag",
    "PageTag",
    "PageNote",
    "Favorite",
    "Collection",
    "CollectionPage",
    "SavedFilter",
    "ScheduledScan",
    "UserSettings",
    "ClassificationTaxonomy",
    "MetaToken",
    "TokenUsageLog",
    "AppSettings",
    "SearchLog",
    "PageSearchHistory",
    "WinningAdSearchHistory",
    "SearchQueue",
    "APICallLog",
    "SuiviPageArchive",
    "AdsRechercheArchive",
    "WinningAdsArchive",
    "APICache",
]
