"""
Module Database - Shim de compatibilite.

Ce module redirige vers src.infrastructure.persistence pour la compatibilite
avec le code existant.
"""

# Re-export depuis la nouvelle localisation
from src.infrastructure.persistence.database import (  # noqa: F401
    # Base SQLAlchemy
    Base,
    CACHE_ENABLED,
    # Classes
    DatabaseManager,
    # Models
    PageRecherche,
    SuiviPage,
    AdsRecherche,
    Blacklist,
    WinningAds,
    Tag,
    PageTag,
    PageNote,
    Favorite,
    Collection,
    CollectionPage,
    SavedFilter,
    ScheduledScan,
    UserSettings,
    ClassificationTaxonomy,
    MetaToken,
    TokenUsageLog,
    AppSettings,
    SearchLog,
    PageSearchHistory,
    WinningAdSearchHistory,
    SearchQueue,
    APICallLog,
    SuiviPageArchive,
    AdsRechercheArchive,
    WinningAdsArchive,
    APICache,
    # Core Functions
    ensure_tables_exist,
    get_etat_from_ads_count,
    to_str_list,
    # App Settings
    get_app_setting,
    set_app_setting,
    get_all_app_settings,
    get_setting,
    set_setting,
    get_all_settings,
    # Pages
    save_pages_recherche,
    batch_insert_pages,
    get_all_pages,
    get_page_history,
    search_pages,
    get_cached_pages_info,
    add_country_to_page,
    add_countries_to_pages_batch,
    get_all_countries,
    get_all_subcategories,
    get_pages_count,
    # Suivi
    save_suivi_page,
    get_suivi_stats,
    get_suivi_stats_filtered,
    get_suivi_history,
    # Dashboard & Evolution
    get_dashboard_trends,
    get_evolution_stats,
    get_page_evolution_history,
    # Ads
    save_ads_recherche,
    # Blacklist
    add_to_blacklist,
    remove_from_blacklist,
    get_blacklist,
    is_in_blacklist,
    get_blacklist_ids,
    bulk_add_to_blacklist,
    # Winning Ads
    is_winning_ad,
    save_winning_ads,
    cleanup_duplicate_winning_ads,
    get_winning_ads,
    get_winning_ads_filtered,
    get_winning_ads_stats_filtered,
    get_winning_ads_stats,
    get_winning_ads_by_page,
    get_winning_ads_by_search_log,
    # Search History
    record_page_search_history,
    record_winning_ad_search_history,
    record_pages_search_history_batch,
    record_winning_ads_search_history_batch,
    get_pages_for_search,
    get_winning_ads_for_search,
    get_searches_for_page,
    get_search_history_stats,
    # Tags
    get_all_tags,
    create_tag,
    delete_tag,
    add_tag_to_page,
    remove_tag_from_page,
    get_page_tags,
    get_pages_by_tag,
    bulk_add_tag,
    # Favorites
    add_favorite,
    remove_favorite,
    toggle_favorite,
    get_favorites,
    is_favorite,
    bulk_add_to_favorites,
    # Collections
    create_collection,
    update_collection,
    delete_collection,
    get_collections,
    add_page_to_collection,
    remove_page_from_collection,
    get_collection_pages,
    get_page_collections,
    bulk_add_to_collection,
    # Notes
    add_page_note,
    update_page_note,
    delete_page_note,
    get_page_notes,
    # Filters
    save_filter,
    get_saved_filters,
    delete_saved_filter,
    # Scheduled Scans
    create_scheduled_scan,
    update_scheduled_scan,
    delete_scheduled_scan,
    get_scheduled_scans,
    mark_scan_executed,
    # Meta Tokens
    add_meta_token,
    update_meta_token,
    delete_meta_token,
    get_all_meta_tokens,
    get_active_meta_tokens,
    get_active_meta_tokens_with_proxies,
    verify_meta_token,
    verify_all_tokens,
    reset_token_stats,
    get_token_stats_detailed,
    # Token Usage
    record_token_usage,
    log_token_usage,
    get_token_usage_logs,
    # Taxonomy
    add_taxonomy_entry,
    update_taxonomy_entry,
    delete_taxonomy_entry,
    get_all_taxonomy,
    get_taxonomy_categories,
    get_taxonomy_by_category,
    init_default_taxonomy,
    build_taxonomy_prompt,
    # Classification
    update_page_classification,
    update_pages_classification_batch,
    get_pages_for_classification,
    get_all_pages_for_classification,
    get_unclassified_pages,
    get_classification_stats,
    # Search Logs
    create_search_log,
    update_search_log,
    update_search_log_phases,
    complete_search_log,
    delete_search_log,
    get_search_logs,
    get_search_logs_stats,
    get_search_log_detail,
    get_pages_by_search_log,
    get_user_searches,
    save_api_calls,
    get_api_calls_for_search,
    # Search Queue
    create_search_queue,
    update_search_queue_status,
    update_search_queue_progress,
    cancel_search_queue,
    restart_search_queue,
    get_search_queue,
    get_pending_searches,
    get_active_searches,
    get_interrupted_searches,
    get_queue_stats,
    recover_interrupted_searches,
    cleanup_old_queue_entries,
    # Cache
    generate_cache_key,
    get_cached_response,
    set_cached_response,
    get_cache_stats,
    clear_expired_cache,
    clear_all_cache,
    clear_rate_limit,
    # Archive
    archive_old_data,
    get_archive_stats,
    cleanup_old_data,
    # Database maintenance
    health_check,
    vacuum_database,
    get_database_stats,
    # Migration helpers
    migration_add_country_to_all_pages,
)

__all__ = [
    # Base
    "Base",
    "CACHE_ENABLED",
    "DatabaseManager",
    # Models
    "PageRecherche",
    "SuiviPage",
    "AdsRecherche",
    "Blacklist",
    "WinningAds",
    "Tag",
    "PageTag",
    "PageNote",
    "Favorite",
    "Collection",
    "CollectionPage",
    "SavedFilter",
    "ScheduledScan",
    "UserSettings",
    "ClassificationTaxonomy",
    "MetaToken",
    "TokenUsageLog",
    "AppSettings",
    "SearchLog",
    "PageSearchHistory",
    "WinningAdSearchHistory",
    "SearchQueue",
    "APICallLog",
    "SuiviPageArchive",
    "AdsRechercheArchive",
    "WinningAdsArchive",
    "APICache",
    # Core Functions
    "ensure_tables_exist",
    "get_etat_from_ads_count",
    "to_str_list",
    # Functions - all exported
    "get_app_setting",
    "set_app_setting",
    "get_all_app_settings",
]
